server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/task_management?useSSL=false&serverTimezone=UTC
    username: root
    password: Manoj@23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # or "create", "create-drop", "validate"
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

# ✅ Move this out from under 'spring'
app:
  base-url: http://localhost:8085
  upload-dir: uploads/

# Optional: Logging for SQL debugging
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE